gates/gates/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    # reieccion la URL raíz a la página de login
    path('', RedirectView.as_view(pattern_name='login', permanent=False)),
    # las URLs de autenticación de Django
    path('accounts/', include('django.contrib.auth.urls')),
    # y se incluye las URLs de la aplicación
    path('gatesApp/', include('gatesApp.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gates/gatesApp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Medico(models.Model):
    ESPECIALIDAD = [
        ('CARDIOLOGO', 'Cardiologo'),
        ('PEDIATRA', 'Pediatra'),
        ('NEUROLOGO', 'Neurologo'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    edad = models.IntegerField()
    imagen = models.ImageField(upload_to='imagen_medico')
    especialidad = models.CharField(max_length=15, choices=ESPECIALIDAD, default='OTRO')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre

class Paciente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    
    # Otros campos y métodos relevantes para Paciente...

    def __str__(self):
        return self.nombre
    
# perfil del paciente
class Perfil(models.Model):
    titulo = models.TextField()
    descripcion = models.CharField(max_length=255)
    medico = models.OneToOneField(Medico, related_name='perfil', on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

# multiples imagenes como tiitulos, displomas etc
class ImagenPerfil(models.Model):
    perfil = models.ForeignKey(Perfil, related_name='imagenesPerfil', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='imagen_perfil')
    descripcion = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    

class Horario(models.Model):
    medico = models.ForeignKey(Medico, related_name='horarios', on_delete=models.CASCADE)
    dia = models.DateField()
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    def __str__(self):
        return f"Horario de {self.medico.nombre} el {self.dia} de {self.hora_inicio} a {self.hora_fin}"

class Cita(models.Model):
    ESTADO = [
        ('DISPONIBLE', 'Disponible'),
        ('CANCELADO', 'Cancelado'),
        ('EJECUTANDOSE', 'Ejecutandose'),
    ]

    medico = models.ForeignKey(Medico, related_name='citas', on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, related_name='citas', on_delete=models.SET_NULL, null=True, blank=True)
    horario = models.ForeignKey(Horario, related_name='citas', on_delete=models.SET_NULL, null=True, blank=True)
    estado = models.CharField(max_length=15, choices=ESTADO, default='DISPONIBLE')
    fecha_hora_inicio = models.DateTimeField()
    fecha_hora_fin = models.DateTimeField()
    motivo_consulta = models.TextField(blank=True, null=True)
    notas = models.TextField(blank=True, null=True)
    
    # Otros campos y métodos relevantes para Cita...

    def __str__(self):
        return f"Cita para {self.medico.nombre} el {self.fecha_hora_inicio.strftime('%Y-%m-%d %H:%M')}"
    

class Servicio(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(0.0)])
    descripcion = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imagen_servicio')
    medico = models.ForeignKey(Medico, related_name='servicios', on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def definir_precio(self, precio):
        self.precio = precio
        return self.save()
    
    # como aparecera en el panel de administracion
    def __str__(self):
        return self.nombre
    


# datos contacto van a estar apgados al consultorio
class Contacto(models.Model):
    descripcion = models.TextField()
    direccion = models.CharField(max_length=255)
    direccion_secundaria = models.CharField(max_length=255, blank=True, null=True)
    correo = models.EmailField()
    telefono = models.CharField(max_length=20) 
    # campos que van a servir para el api google maps
    latitud = models.FloatField(null=True, blank=True)  # Nuevo campo para latitud
    longitud = models.FloatField(null=True, blank=True)  # Nuevo campo para longitud
    medico = models.OneToOneField(Medico, related_name='contacto', on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

# multiples imagenes como lugares referenciales etc
class ImagenContacto(models.Model):
    contacto = models.ForeignKey(Contacto, related_name='imagenesContacto', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='imagen_contacto')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

gates/templates/base.html
<html lang="en">
    <head>
        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Business Casual - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/bootstrap/css/styles.css' %}" rel="stylesheet">

        <link href="{% static 'css/gates.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">A Free Bootstrap Business Theme</span>
                <span class="site-heading-lower">Business Casual</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        
                        {% if request.user.is_authenticated %}
                            
                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase" href="{% url 'medicoHome' username=request.user.username %}">Home</a>
                            </li>

                            <!-- para odifiacr campos del medico -->
                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase" href="{% url 'medicoActualizar' username=request.user.username %}">Mi Perfil</a>
                            </li>
                    
                            <!-- para la sección de sobreNos -->

                            <li class="nav-item px-lg-4">
                                {% if medico.perfil %}
                                    <a class="nav-link text-uppercase" href="{% url 'perfilDetalle' username=request.user.username %}">Ver Sobre mi</a>
                                {% else %}
                                    <a class="nav-link text-uppercase" href="{% url 'perfilSubir' username=request.user.username %}">Subir Sobre mi</a>
                                {% endif %}
                            </li>


                            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'servicios' username=user.username %}">Servicios</a></li>


                            <li class="nav-item px-lg-4">
                                {% if medico.contacto %}
                                    <a class="nav-link text-uppercase" href="{% url 'contactoDetalle' username=request.user.username %}">Ver Contacto</a>
                                {% else %}
                                    <a class="nav-link text-uppercase" href="{% url 'contactoSubir' username=request.user.username %}">Subir Contacto</a>
                                {% endif %}
                            </li>


                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Cerrar sesión</button>
                            </form>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- aqui en esta seccion se va a poer el contenido cambiante -->
        {% block content %}

        {% endblock %}
        <!--  fin del contenido cambiante quesufriran en los hijos-->

        <section class="page-section about-heading">
            <div class="container">
                <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'assets/img/about.jpg' %}" alt="..." />
                <div class="about-heading-content">
                    <div class="row">
                        <div class="col-xl-9 col-lg-10 mx-auto">
                            <div class="bg-faded rounded p-5">
                                <h2 class="section-heading mb-4">
                                    <span class="section-heading-upper">Especialista medico nota: poner nombre</span>
                                    <span class="section-heading-lower">Sobre nuestros servicios medicos</span>
                                </h2>
                                <p>Nota: Ubicacion de un parrafo introductorio</p>
                                <p class="mb-0">
                                    Nota opcional: poner algo
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'vendor/bootstrap/js/scripts.js' %}"></script>
    </body>
</html>

gates/templates/contactoActualizar.html
{% extends 'base.html' %}
{% block content %}
<h2>Actualizar Información de Contacto</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ miFormularioContacto.as_p }}
  {{ miFormularioImagenesContacto.management_form }}
  {% for form in miFormularioImagenesContacto %}
    {% if form.instance.pk %}
      <img src="{{ form.instance.imagen.url }}" alt="Imagen actual" />
      <p>Eliminar? {{ form.DELETE }}</p>
    {% endif %}
    {{ form.as_p }}
  {% endfor %}
  <button type="submit">Actualizar Contacto</button>
</form>

Username: {{ username }}

{% endblock %}

gates/templates/contactoDetalle.html
{% extends 'base.html' %}
{% block content %}
  <h2>Detalle de Contacto</h2>
  <p>{{ contacto.descripcion }}</p>
  <p>{{ contacto.direccion }}</p>
  <p>{{ contacto.correo }}</p>
  <p>{{ contacto.telefono }}</p>
  <!-- Aquí iría la implementación de la API de Google Maps para la latitud y longitud -->
  {% for imagen in imagenes %}
    <img src="{{ imagen.imagen.url }}" alt="Imagen de contacto" />
  {% endfor %}
  <a href="{% url 'contactoActualizar' username=username %}">Actualizar Contacto</a>

  Username: {{ username }}

{% endblock %}

gates/templates/contactoSubir.html
{% extends 'base.html' %}
{% block content %}
<h2>Subir Información de Contacto</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ miFormularioContacto.as_p }}
  {{ miFormularioImagenesContacto.management_form }}
  {% for form in miFormularioImagenesContacto %}
    {{ form.as_p }}
  {% endfor %}
  <button type="submit">Guardar Contacto</button>
</form>

Username: {{ username }}

{% endblock %}

gates/templates/home.html
<!-- se indic que va a heredar de base.html -->
{% extends "base.html" %}

<!-- se carga lo que esta en la carpeta static -->
{% load static %}  

<!-- aqui va el contenido cambiante -->
{% block content %}

    {% if medico %}
        <h1>Bienvenido, Dr. {{ medico.nombre }}</h1>
        <p>{{ medico.descripcion }}</p>
        <!-- Aquí puedes añadir más detalles, como una imagen, especialidad, etc. -->
        <img src="{{ medico.imagen.url }}" alt="Imagen de perfil">
        <p>Especialidad: {{ medico.get_especialidad_display }}</p>

        <!-- Y enlaces a las otras secciones -->

        <!-- etc. -->
    {% else %}
        <p>Perfil de médico no encontrado.</p>
    {% endif %}

{% endblock %}

gates/templates/login.html
{% extends 'base.html' %}

{% block content %}
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'login' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
  </form>

  <a href="{% url 'registerMedico' %}">Register</a>
{% endblock %}

gates/templates/medicoActualizar.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Actualizar mis datos</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioMedico.as_p }}
        <button type="submit" class="btn btn-primary">Actualizar datos</button>
    </form>
</div>
{% endblock %}

gates/templates/medicoFormSubir.html
{% extends "base.html" %}

{% load static %}  
{% load crispy_forms_tags %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioMedico.as_p }}
        <button type="submit">Add Profile</button>
    </form>
{{request.POST}}

{% endblock %}

gates/templates/perfilActualizar.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Perfil</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioPerfil.as_p }}
        {{ miFormularioImagenesPerfil.management_form }}
            {% for form in miFormularioImagenesPerfil %}
                {% if form.instance.pk %}
                    <img src="{{ form.instance.imagen.url }}" alt="Imagen actual" />
                    <p>Eliminar? {{ form.DELETE }}</p>
                {% endif %}
            {{ form.as_p }}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>
</div>
{% endblock %}

gates/templates/perfilSubir.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Subir Perfil</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioPerfil.as_p }}
        {{ miFormularioImagenesPerfil }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

gates/templates/servicioActualizar.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Actualizar servicio</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioServicio.as_p }}
        <button type="submit" class="btn btn-primary">Actualizar servicio</button>
    </form>
</div>
{% endblock %}

gates/templates/servicioSubir.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Subir Comida</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormularioServicio.as_p }}
        <button type="submit" class="btn btn-primary">Guardar Comida</button>
    </form>
</div>
{% endblock %}

gates/templates/servicios.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Servicios</h2>
        <ul>
            {% for servicio in servicios_list %}
                <li>
                    {{ servicio.nombre }} - 
                    <div>
                        <img src="{{ servicio.imagen.url }}" alt="Imagen de {{ servicio.nombre }}" width="300">
                    </div>
                    <a href="{% url 'servicioDetalle' username=username id=servicio.id %}">Ver Detalles</a> |
                    <a href="{% url 'servicioActualizar' username=username id=servicio.id %}">Editar</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'servicioSubir' username=username %}" class="btn btn-primary">Agregar servicio</a>
    </div>
{% endblock %}

gates/templates/subir.html
<!-- se indic que va a heredar de base.html -->
{% extends "base.html" %}

<!-- se carga lo que esta en la carpeta static -->
{% load static %}  

<!-- aqui va el contenido cambiante -->
{% block content %}

<!-- boton de cancelar -->
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
    <button type="button" class="btn btn-danger">Danger</button>
    <div class="btn-group" role="group">
      <button id="btnGroupDrop4" type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop4">
        <a class="dropdown-item" href="#">Dropdown link</a>
        <a class="dropdown-item" href="#">Dropdown link</a>
      </div>
    </div>
</div>
 


<div class="contenedorFormulario">

    {% if "valid" in request.GET %}
        <p>subida correcta</p>
    {% endif %}

    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table style="color: white; margin: 20px auto;">
            {{miFormulario.as_table}}
        </table>
        <input type="submit" style="width: 150px;" value="Enviar">
    </form>
</div>
{{request.POST}}

{% endblock %}